"""changed schema

Revision ID: a727b0c93e28
Revises: f3b777bc8218
Create Date: 2024-09-10 18:53:58.394903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a727b0c93e28'
down_revision = 'f3b777bc8218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_creator_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_threads_thread_receiver_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_threads_thread_creator_id_users'), 'users', ['thread_creator_id'], ['id'])
        batch_op.drop_column('thread_receiver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_receiver_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_threads_thread_creator_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_threads_thread_receiver_id_users', 'users', ['thread_receiver_id'], ['id'])
        batch_op.drop_column('thread_creator_id')

    # ### end Alembic commands ###
