"""revised thread schema

Revision ID: afdda6b6d5d0
Revises: 476cd8d01b9e
Create Date: 2024-09-10 20:23:38.728468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdda6b6d5d0'
down_revision = '476cd8d01b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_receiver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_threads_thread_receiver_id_users'), 'users', ['thread_receiver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_threads_thread_receiver_id_users'), type_='foreignkey')
        batch_op.drop_column('thread_receiver_id')

    # ### end Alembic commands ###
